# Generated by Django 5.1.1 on 2025-03-08 01:05

import test_s3.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(storage=test_s3.storage.PublicMediaStorage(), upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
